# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mrf_C <- function(Theta, nui, B) {
    .Call(`_jointBART_mrf_C`, Theta, nui, B)
}

up_relatedness <- function(adj, Theta, nu, alpha, beta, my_w, B, accep_gamma, accep_theta, within_model) {
    invisible(.Call(`_jointBART_up_relatedness`, adj, Theta, nu, alpha, beta, my_w, B, accep_gamma, accep_theta, within_model))
}

up_nu <- function(nu, adj, Theta, a, b, B, accep_nu) {
    invisible(.Call(`_jointBART_up_nu`, nu, adj, Theta, a, b, B, accep_nu))
}

JointBart <- function(n, p, np, x, y, xp, m, nc, nd, burn, mybeta, alpha, tau, nu, lambda, sigma, w, dart, theta, omega, igrp, a, b, rho, aug, iXinfo, Theta, adj, graph_nu, B, graph_alpha, graph_beta, my_w, graph_a, graph_b, adj_alpha0, adj_alpha1, Joint) {
    .Call(`_jointBART_JointBart`, n, p, np, x, y, xp, m, nc, nd, burn, mybeta, alpha, tau, nu, lambda, sigma, w, dart, theta, omega, igrp, a, b, rho, aug, iXinfo, Theta, adj, graph_nu, B, graph_alpha, graph_beta, my_w, graph_a, graph_b, adj_alpha0, adj_alpha1, Joint)
}

JointBartB <- function(n, p, np, x, y, xp, m, nc, nd, burn, mybeta, alpha, binaryOffset, tau, dart, theta, omega, igrp, a, b, rho, aug, iXinfo, Theta, adj, graph_nu, B, graph_alpha, graph_beta, my_w, graph_a, graph_b, adj_alpha0, adj_alpha1, Joint) {
    .Call(`_jointBART_JointBartB`, n, p, np, x, y, xp, m, nc, nd, burn, mybeta, alpha, binaryOffset, tau, dart, theta, omega, igrp, a, b, rho, aug, iXinfo, Theta, adj, graph_nu, B, graph_alpha, graph_beta, my_w, graph_a, graph_b, adj_alpha0, adj_alpha1, Joint)
}

rcpp_hello <- function() {
    .Call(`_jointBART_rcpp_hello`)
}

