# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

JointBart <- function(n, p, np, x, y, xp, m, nc, nd, burn, mybeta, alpha, tau, nu, lambda, sigest, w, dart, theta, omega, igrp, a, b, rho, aug, keeptrain, keeptest, keeptestme, keeptreedraws, printevery, iXinfo) {
    invisible(.Call(`_jointBART_JointBart`, n, p, np, x, y, xp, m, nc, nd, burn, mybeta, alpha, tau, nu, lambda, sigest, w, dart, theta, omega, igrp, a, b, rho, aug, keeptrain, keeptest, keeptestme, keeptreedraws, printevery, iXinfo))
}

rcpp_hello <- function() {
    .Call(`_jointBART_rcpp_hello`)
}

